### ISSUE TITLE
Remove the need of .default when importing in JS

### ISSUE THREAD

**Issue by mingchuno** [jdesboeufs/connect-mongo#405]
Remove `export default` so that when importing in JS, no need to add extra `.deafult`?
But I don't want to introduce extra setup on webpack / rollup. 
Maybe use named export instead?

### Current behavior

In TS:
```ts
export default MongoStore
```
Imporing in JS:
```js
const MongoStore = require('connect-mongo').default
```

### Option 1

In TS:
```ts
export const MongoStore
```
Imporing in JS:
```js
const { MongoStore } = require('connect-mongo')
``` 

### Option 2
Include webpack/rollup?

In TS:
```ts
export default MongoStore
```
Imporing in JS:
```js
const MongoStore= require('connect-mongo')
``` 

### TODOs:
---
- [ ] Add typescript example
- [ ] Study the effect to remove default export
- [ ] Study can we keep the default export but keep the JS import simple
- [ ] Update documentation on importing
